# 
FROM python:{{cookiecutter.runtime}}

# 
WORKDIR /build

# 
COPY ./requirements.txt /build/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /build/requirements.txt

# 
COPY ./app /build/app

# 
CMD ["uvicorn", "app.api.main:app", "--host", "0.0.0.0", "--port", "80"]
